sudo: required
dist: trusty
language: python
cache:
- pip
- apt
python:
- 2.7
- 3.6
install:
- pip install -r dev_requirements.txt
script:
- python setup.py test
- python setup.py sdist bdist bdist_wheel
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: lh85XhX1gB9V3BIvx4Fco5ESNZwXgn0nQwPqVZxMiHEl43O5NCF2Aaq13OQBui5CpCrI8yK3DpAUV3C9YdWnpvkHefIf8+9pgHt0574tjH8n+lfHWCAhHobMmdqZ05sZ+GNt8x/9CQFkguHvR8HQ6hLL0Ag3Qo0G2FFr9Opt8SXsd6pBsRZYp5E/18uZb+51ScKoPff8XsPJ6ybzH7ls1wfxVh9nSTwB+/AgCuaXYd8kiJcvOy7ZZUEYw8EYo9yWOO1i4fbdaanzXB9pzUEw9XyisshFm6Ag8/Vhlzc8DxMOG7z6ZRj3xJHcU3qAT+6/6IdEGy5LsTT5a3KDOl2CvOdzES6wiSwKsK0JBWkxUwwMC0VYDTGLz50G+qOfeqQhPPnsb5S/aBIIKZMUe43L7riZazU0zgEy5mgNDQuTttlikFczd4169pYh15OZpHWCNbzEbuEsiOZ5ps7McFdIgA0EAqg4YhCNQp6BEP6POJu/oXtbns0KLTMEKVBnWgF6o70JGSXKUwlvY1MHMKnooLYTfb3/levhYdPFdUC8SWPme9KnWvjQJke7TNfwluBn9QsxeiWtQdTuU5ZXjDfK7dp20n/2Y8+3CJwEp6tDLnjOGRox+DEuw1HlbE3rOEHPufGCFMX8zVsvVmBooLgqSJ0w4NvVgdeoDPUSUxPSJwI=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
